#pragma once

#include "gen/config.h"

namespace pacman {

namespace Config {
	
	static const int
		MOVEMENT_SPEED = 8,
		MOVEMENT_SPEED_SLOW = 4,
		MOVEMENT_SPEED_EXIT_HOUSE = 4,
		MOVEMENT_SPEED_FAST = 16,
		SPAWN_TIME = 15,
		FLEEING_TIME = 4,
		WARNING_TIME = 2,
		ANIMATION_SPEED_PACMAN = 50,
		ANIMATION_SPEED_PACMAN_DEATH = 150,
		ANIMATION_SPEED_GHOST = 150,
		ANIMATION_SPEED_POWER_UP = 200,
		SPRITE_SIZE = 16,
		TILE_SIZE = 8,
		WIN_FLASH_SPEED = 250,

		WINDOW_WIDTH = GEN_CONFIG_SCREEN_WIDTH,
		WINDOW_HEIGHT = GEN_CONFIG_SCREEN_HEIGHT,
		WINDOW_SCALE = 3,

		START_EXTRA_LIFE = 1,

		POINT_PELLET = 1,
		POINT_POWER_UP = 5,
		POINT_GHOST = 20,
		ONE_UP_AT = 1000,

		MAX_SCORES = 5,
		START_SCORE = 100,

		LEVEL_WIDTH = GEN_CONFIG_LEVEL_WIDTH,
		LEVEL_HEIGHT = GEN_CONFIG_LEVEL_HEIGHT,
		HOUSE_Y = 14,
		HOUSE_EXIT_Y = 11
		;
	static const float
		FRUIT_ACTIVE_TIME = 8.0f,
		FRUIT_DESPAWN_TIME = 2.0f,
		FRUIT_SPAWN_TIME = 12.0f,
		PAUSE_TIME = 1.0f,
		WIN_PAUSE_TIME = 1.0f,
		WIN_ANIMATION_LENGTH = 2.0f,
		TEXT_FLASH_SPEED = 0.25f,
		LEVEL_CENTER = LEVEL_WIDTH / 2.0f - 0.5f
		;
}

}; // namespace pacman
